'use strict';

export const GET_WEB_EDITION = 'GET_WEB_EDITION';
export const GET_WEB_EDITION_SUCCESSE = 'GET_WEB_EDITION_SUCCESSE';

export const GET_ITEMS = 'GET_ITEMS';
export const GET_ITEMS_SUCCESSE = 'GET_ITEMS_SUCCESSE';