'use strict';

export const GET_ITEMS = 'GET_ITEMS';
export const GET_ITEMS_SUCCESSE = 'GET_ITEMS_SUCCESSE';

export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const GET_ACCESS_TOKEN_SUCCESSE = 'GET_ACCESS_TOKEN_SUCCESSE';

export const GET_USER_ITEMS = 'GET_USER_ITEMS';
export const GET_USER_ITEMS_SUCCESSE = 'GET_USER_ITEMS_SUCCESSE';
